version: '3.9'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    
    env_file:
      - .env
    
    # or 
    # environment:
      #- BACKEND_PORT=7001   # if you change the port, make sure to also change the VITE_WS_BACKEND_URL at frontend/.env.local
      # - OPENAI_API_KEY=your_openai_api_key
    
    ports:
      - "${BACKEND_PORT:-7001}:${BACKEND_PORT:-7001}"

    command: poetry run uvicorn main:app --host 0.0.0.0 --port ${BACKEND_PORT:-7001} --workers 2
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"

  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/xanxushu/nginx:latest
    restart: always
    depends_on:
      - backend
      - frontend
    ports:
      - "80:5173" 
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # 挂载自定义的nginx配置文件